# Set up environment variables for tests
env:
  global:
    # Use a better mocha reporter for Travis
    - MOCHA_REPORTER=spec
# Use the Travis Docker build system which is faster
sudo: false
# Specify to use node
language: node_js
# Specify the node versions to run on
node_js:
  - 14
install:
  - npm install
  - npm run vscode:prepublish